server:
  port: 8081

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yeb?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
    username: root
    password: root

#    redis配置
  redis:
#    超时时间
    timeout: 10000ms
#    服务器地址
    host: 127.0.0.1
#    端口号
    port: 6379
#    数据库
    database: 0 # 选择哪个库，默认0库
    lettuce:
      pool:
        max-active: 1024 # 最大连接数，默认 8
        max-wait: 10000ms # 最大连接阻塞等待时间，单位毫秒，默认 -1
        max-idle: 200 # 最大空闲连接，默认 8
        min-idle: 5

  # rabbitmq配置
  rabbitmq:
    username: guest
    password: guest
    host: 127.0.0.1
    port: 5672
    # 消息确认回调
    publisher-confirm-type: correlated
    # 消息失败回调
    publisher-returns: true


mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #配置mybatis数据返回类型别名
  type-aliases-package: com.example.server.pojo
  configuration:
    # 自动驼峰命名
    map-underscore-to-camel-case: false

#打印mysql语句   (接口所在位置  不是mappering.xml文件位置)
logging:
  level:
    com.example.server.mapper: debug

#配置jwt
jwt:
  # Jwt存储的请求头
  tokenHeader: Authorization
  # Jwt加密秘钥
  secret: yeb-secret
  # Jwt 的超期限时间（60*60）*24   24小时
  expiration: 604800
  # Jwt负载中拿到开头
  tokenHead: Bearer